In [ ]:
!pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "austinreese/craigslist-carstrucks-data",
    "vehicles.csv"
)

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

/tmp/ipykernel_267/3667461775.py:6: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/austinreese/craigslist-carstrucks-data?dataset_version_number=10&file_name=vehicles.csv...

100%|██████████| 262M/262M [00:01<00:00, 144MB/s]

Extracting zip of vehicles.csv...

In [ ]:
display (df.head())
df.info()
print(df.isnull().sum())

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   url           426880 non-null  object
 2   region        426880 non-null  object
 3   region_url    426880 non-null  object
 4   price         426880 non-null  int64
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object
 7   model         421603 non-null  object
 8   condition     252776 non-null  object
 9   cylinders     249202 non-null  object
 10  fuel          423867 non-null  object
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object
 13  transmission  424324 non-null  object
 14  VIN           265838 non-null  object
 15  drive         296313 non-null  object
 16  size          120519 non-null  object
 17  type          334022 non-null  object
 18  paint_color   296677 non-null  object
 19  image_url     426812 non-null  object
 20  description   426810 non-null  object
 21  county        0 non-null       float64
 22  state         426880 non-null  object
 23  lat           420331 non-null  float64
 24  long          420331 non-null  float64
 25  posting_date  426812 non-null  object
dtypes: float64(5), int64(2), object(19)
memory usage: 84.7+ MB
id                   0
url                  0
region               0
region_url           0
price                0
year              1205
manufacturer     17646
model             5277
condition       174104
cylinders       177678
fuel              3013
odometer          4400
title_status      8242
transmission      2556
VIN             161042
drive           130567
size            306361
type             92858
paint_color     130203
image_url           68
description         70
county          426880
state                0
lat               6549
long              6549
posting_date        68
dtype: int64

In [ ]:
print("temizlik öncesi veri boyutu:", df.shape)

silinecek_surunlar = ['id','url', 'region_url', 'image_url', 'county', 'vin']
df.drop(columns=silinecek_surunlar, errors='ignore')
df = df.dropna(subset=['price','manufacturer','model','price'])
df = df[(df['price'] >= 500)& (df['price'] <= 100000)]
print("temizlik sonrası kalan veri boyutu:", df.shape)

temizlik öncesi veri boyutu: (426880, 26)
temizlik sonrası kalan veri boyutu: (364263, 26)

In [ ]:
from sklearn.preprocessing import LabelEncoder

kategorik_sutunlar = df.select_dtypes(include=['object']).columns
df[kategorik_sutunlar] = df[kategorik_sutunlar].fillna('belirtilmemiş')
le = LabelEncoder()
for sutun in kategorik_sutunlar:
  df[sutun] = le.fit_transform(df[sutun])

print("Dönüşüm sonrası veri tipleri:")
df.info()

display(df.head())

Dönüşüm sonrası veri tipleri:
<class 'pandas.core.frame.DataFrame'>
Index: 364263 entries, 27 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            364263 non-null  int64
 1   url           364263 non-null  int64
 2   region        364263 non-null  int64
 3   region_url    364263 non-null  int64
 4   price         364263 non-null  int64
 5   year          364259 non-null  float64
 6   manufacturer  364263 non-null  int64
 7   model         364263 non-null  int64
 8   condition     364263 non-null  int64
 9   cylinders     364263 non-null  int64
 10  fuel          364263 non-null  int64
 11  odometer      362266 non-null  float64
 12  title_status  364263 non-null  int64
 13  transmission  364263 non-null  int64
 14  VIN           364263 non-null  int64
 15  drive         364263 non-null  int64
 16  size          364263 non-null  int64
 17  type          364263 non-null  int64
 18  paint_color   364263 non-null  int64
 19  image_url     364263 non-null  int64
 20  description   364263 non-null  int64
 21  county        0 non-null       float64
 22  state         364263 non-null  int64
 23  lat           360953 non-null  float64
 24  long          360953 non-null  float64
 25  posting_date  364263 non-null  int64
dtypes: float64(5), int64(21)
memory usage: 75.0 MB

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
27,7316814884,18624,16,18,33590,2014.0,14,17272,3,6,...,0,9,11,82911,178896,NaN,1,32.590,-85.4800,316922
28,7316814758,18608,16,18,22590,2010.0,7,17634,3,6,...,0,9,2,82911,208217,NaN,1,32.590,-85.4800,316904
29,7316814989,18708,16,18,39590,2020.0,7,17678,3,6,...,0,9,9,191870,197255,NaN,1,32.590,-85.4800,316935
30,7316743432,18662,16,18,30990,2017.0,38,20369,3,6,...,0,9,9,174505,177330,NaN,1,32.590,-85.4800,312845
31,7316356412,18732,16,18,15000,2013.0,13,8781,1,5,...,2,11,1,14520,78640,NaN,1,32.592,-85.5189,293439

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

#modeli x ve ye olarak iki parçaya bölüyoruz
X = df.drop(columns=['price'])
y = df['price']
#Eğitime %80 ve teste %20 olarka parçaladık
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Modele çalışması için gereken araç sayısı: {len(X_train)}")
print(f"Modelin teste tabi olması için gereken araç sayısı: {len(X_test)}")

print("\nModel kuruluyor")
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs = -1)
model.fit(X_train, y_train)

tahminler = model.predict(X_test)

mae = mean_absolute_error(y_test, tahminler)
r2 = r2_score(y_test, tahminler)

print(f"Ortalama Mutlak Hata (MAE): {mae:.0f} Dolar")
print(f"R2 Skoru: %{r2*100:.1f}")

Modele çalışması için gereken araç sayısı: 291410
Modelin teste tabi olması için gereken araç sayısı: 72853

Model kuruluyor
Ortalama Mutlak Hata (MAE): 1947 Dolar
R2 Skoru: %91.2

In [ ]:
ornek_arabalar = X_test.sample(3, random_state = 80)
gerçek_fiyatlar = y_test.loc[ornek_arabalar.index]

tahmin_edilen_fiyatlar = model.predict(ornek_arabalar)

for i in range(3):
  print(f"Araç {i+1}:")
  print(f"Gerçekte istenen fiyat : {gerçek_fiyatlar.iloc[i]}Dolar")
  print(f"Modelin tahmini : {tahmin_edilen_fiyatlar[i]:.0f}Dolar")
  print(f"Aradaki fark : {abs(gerçek_fiyatlar.iloc[i] - tahmin_edilen_fiyatlar[i]):.0f}Dolar")

print("-"* 30)

Araç 1:
Gerçekte istenen fiyat : 12900Dolar
Modelin tahmini : 13154Dolar
Aradaki fark : 254Dolar
Araç 2:
Gerçekte istenen fiyat : 27990Dolar
Modelin tahmini : 27990Dolar
Aradaki fark : 0Dolar
Araç 3:
Gerçekte istenen fiyat : 13980Dolar
Modelin tahmini : 13928Dolar
Aradaki fark : 52Dolar
------------------------------